eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
server:
  port: 8301

#upload:
#  path: /uanfun/upload
#  server: http://127.0.0.1:8762

#test
upload:
  path: /star/upload
spring:
  application:
    name: knowledge-provider
  http:
    multipart:
      max-file-size: 20Mb      # Max file size，默认1M
      max-request-size: 20Mb   # Max request size，默认10M
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/study-interview
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 20000
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
mybatis:
    mapperLocations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml

logging:
  level:
    com:
      xinyuegu:
        star:
          knowledge:
            mapper: debug